# Goal - I have to ensure the packages & dependencies have been audited for Security

name: Dependecy scan

on:
    workflow_call:

jobs:
    dependency-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v7

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                cache: TRUE
                go-version: '1.23'
                cache-dependency-path: backend/go.sum

            - name: Install Govulncheck
              run: go install golang.org/x/vuln/cmd/govulncheck@v1.1.3

            # Creates the reports directory inside 'backend' and saves Go report
            - name: GoVulncheck
              continue-on-error: true
              run: |
                  mkdir -p reports
                  govulncheck ./... > reports/govulncheck-report.txt
              working-directory: backend

            # Setup Nodejs
            - name: Setup NodeJs
              uses: actions/setup-node@v5
              with:
                node-version: '22'
                cache: npm
                cache-dependency-path: 'frontend/package-lock.json'

            # Dependency ssan for node
            - name: Run Dependency Scan for Node
              continue-on-error: true
              run: npm audit --audit-level=high > ../backend/reports/node-audit-report.txt
              working-directory: frontend

              # upload artifacts to github repository
            - name: Upload Report to Artifacts
              if: always() # Ensures report uploads even if tests fail
              uses: actions/upload-artifact@v4
              with:
                name: dependency-scan-report
                path: backend/reports/
                retention-days: 5
                if-no-files-found: ignore # This suppresses the warning if the file is missing.